apiVersion: v1
kind: Pod
metadata:
  name: playwright-test-pod
spec:
  restartPolicy: Never
  containers:
    - name: playwright
      image: gangadhar66/playwright-tests:b0e936a8006be042df90c9480db9fc89ea0413e5
      imagePullPolicy: Always
