apiVersion: v1
kind: Pod
metadata:
  name: playwright-test-pod
spec:
  restartPolicy: Never
  containers:
    - name: playwright
      image: gangadhar66/playwright-tests:0eb0c3bc23116afb00d76a8bc30b6c87c09b007b
      imagePullPolicy: Always
