apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-tests
  labels:
    app: playwright-tests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playwright-tests
  template:
    metadata:
      labels:
        app: playwright-tests
    spec:
      restartPolicy: Always
      containers:
        - name: playwright
          image: gangadhar66/playwright-tests:641baf805df188d3f8cd5647473e28abb7cc1e1e
          imagePullPolicy: Always
