apiVersion: v1
kind: Pod
metadata:
  name: playwright-test-pod
spec:
  restartPolicy: Never
  containers:
    - name: playwright
      image: gangadhar66/playwright-tests:6bd5678030599c1e8e74b0d60fe0868c86af2d70
      imagePullPolicy: Always
