apiVersion: v1
kind: Pod
metadata:
  name: test-image
spec:
  containers:
  - name: test-container
    image: 473259746718.dkr.ecr.ap-south-1.amazonaws.com/playwright-tests:latest
    imagePullPolicy: Never

